name: AdalReklam
version: 1.0.0
main: com.adalreklam.AdalReklamPlugin
api-version: 1.20
author: YourName
description: Webhook destekli profesyonel reklam sistemi
website: https://yourwebsite.com

depend: [Vault]

commands:
  reklam:
    description: Reklam satın alma menüsünü açar
    usage: /<command>
    aliases: [ad, advertisement]

  reklamadmin:
    description: Admin komutları
    usage: /<command> <reload|logs|stats|setprice>
    aliases: [radmin, adadmin]
    permission: adalreklam.admin

permissions:
  adalreklam.use:
    description: Reklam satın alabilir
    default: true

  adalreklam.admin:
    description: Admin komutlarını kullanabilir
    default: op
    children:
      adalreklam.use: true
      adalreklam.bypass.cooldown: true

  adalreklam.bypass.cooldown:
    description: Cooldown'ı atlar
    default: op